### ISSUE TITLE
frida.TimedOutError : ~

### ISSUE THREAD

**Issue by kokoory** [chame1eon/jnitrace#27]
Hi, I am using frida 14.2.8 & python 3.6. 
my devices is galaxy s9+, so 64bits of frida-server is running on devices.
but when I have try to use, the error occurred .

----------------------------------------
jnitrace -l libDrm2.so com.appName
------Error----------------------------------------
Traceback (most recent call last):
  File "c:\users\des\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\des\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\des\AppData\Local\Programs\Python\Python36\Scripts\jnitrace.exe\__main__.py", line 9, in <module>
  File "c:\users\des\appdata\local\programs\python\python36\lib\site-packages\jnitrace\jnitrace.py", line 565, in main
    pid = device.spawn([args.target], **aux_kwargs)
  File "c:\users\des\appdata\local\programs\python\python36\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "c:\users\des\appdata\local\programs\python\python36\lib\site-packages\frida\core.py", line 140, in spawn
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
frida.TimedOutError: unexpectedly timed out while waiting for app to launch

**Comment by kokoory** [comment]
I think it is not working on 64bit

**Comment by chame1eon** [comment]
Hi,

Are you able to run ordinary Frida script on your device? Or is it specifically an issue with jnitrace?

Also, can you try and see if the '-m attach' option works better than the default?

Thanks

**Comment by chame1eon** [comment]
Closing as not heard in over a month
