### ISSUE TITLE
Attach mode maybe has some bugs

### ISSUE THREAD

**Issue by mywonson** [chame1eon/jnitrace#51]
When using attach mode,jnitrace can't find the target process although that target process is running all the time:
Traceback (most recent call last):
  File "H:\python\program\Scripts\jnitrace-script.py", line 11, in <module>
    load_entry_point('jnitrace==3.3.0', 'console_scripts', 'jnitrace')()
  File "h:\python\program\lib\site-packages\jnitrace\jnitrace.py", line 584, in main
    pid = device.get_process(args.target).pid
  File "h:\python\program\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "h:\python\program\lib\site-packages\frida\core.py", line 121, in get_process
    raise _frida.ProcessNotFoundError("unable to find process with name '%s'" % process_name)
frida.ProcessNotFoundError: unable to find process with name 'com.hxyh.wxamp3'
Frida 15.1.16 - A world-class dynamic instrumentation toolkit

**Comment by 0xuu3389** [comment]
frida 15 version after the need to use the process name injection
