### ISSUE TITLE
jnitrace execution error

### ISSUE THREAD

**Issue by mscgo** [chame1eon/jnitrace#8]
Hello

I am trying to execute jnitrace with python3.8 environment

it shows below

Traceback (most recent call last):
  File "C:\Users\a\AppData\Local\Programs\Python\Python38\Scripts\jnitrace-script.py", line 11, in <module>
    load_entry_point('jnitrace==3.0.0', 'console_scripts', 'jnitrace')()
  File "C:\Users\a\AppData\Local\Programs\Python\Python38\lib\site-packages\jnitrace-3.0.0-py3.8.egg\jnitrace\jnitrace.py", line 519, in main
  File "C:\Users\a\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 1156, in resource_string
    return get_provider(package_or_requirement).get_resource_string(
  File "C:\Users\a\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 361, in get_provider
    __import__(moduleOrReq)
ModuleNotFoundError: No module named 'jnitrace.build'

can you take this issue?

**Comment by chame1eon** [comment]
Hi,

Thanks for submitting an issue.

I have been unable to reproduce the same issue. I also tried running with a python38 environment and on Windows.

How are you installing jnitrace, is it through pip?

Thanks

**Comment by mscgo** [comment]
Thanks for your quick response.

I removed jnitrace package and reinstalled. then it works.

Thanks for your reply :)

**Comment by Awekbing** [comment]
thanks mscgo  ,it works well
这玩意真是666啊
